---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: spring-boot-app
  namespace: default
  labels:
    app: spring-boot-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-app
  template:
    metadata:
      labels:
        app: spring-boot-app
    spec:
      containers:
      - name: spring-boot-app
        image: "abhilashnarayan/spring-boot-docker.jar:latest"
        ports:
          - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-app
  namespace: default
spec:
  selector:
    app: spring-boot-app
  type: LoadBalancer
  ports:
  - name: http
    targetPort: 3000
    port: 80
